// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ticari.Entities.DBContexts;

#nullable disable

namespace Ticari.Entities.Migrations.Turkiye
{
    [DbContext(typeof(TurkiyeContext))]
    [Migration("20241106071924_turkiyedb")]
    partial class turkiyedb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ticari.Entities.TurkiyeDb.TblIl", b =>
                {
                    b.Property<short>("IlId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("il_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("IlId"));

                    b.Property<string>("IlAd")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("il_ad")
                        .UseCollation("Turkish_CI_AS");

                    b.HasKey("IlId")
                        .HasName("PK_tbl_iller");

                    b.ToTable("tbl_il", (string)null);
                });

            modelBuilder.Entity("Ticari.Entities.TurkiyeDb.TblIlce", b =>
                {
                    b.Property<short>("IlceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("ilce_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("IlceId"));

                    b.Property<short>("IlId")
                        .HasColumnType("smallint")
                        .HasColumnName("il_id");

                    b.Property<string>("IlceAd")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("ilce_ad")
                        .UseCollation("Turkish_CI_AS");

                    b.HasKey("IlceId");

                    b.HasIndex(new[] { "IlceId", "IlId" }, "IX_ilce");

                    b.ToTable("tbl_ilce", (string)null);
                });

            modelBuilder.Entity("Ticari.Entities.TurkiyeDb.TblMahalle", b =>
                {
                    b.Property<int>("MahalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("mahalle_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MahalleId"));

                    b.Property<string>("MahalleAd")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("mahalle_ad")
                        .UseCollation("Turkish_CI_AS");

                    b.Property<short?>("PkId")
                        .HasColumnType("smallint")
                        .HasColumnName("pk_id");

                    b.Property<short>("SemtId")
                        .HasColumnType("smallint")
                        .HasColumnName("semt_id");

                    b.HasKey("MahalleId");

                    b.HasIndex(new[] { "MahalleId", "SemtId" }, "IX_mahalle");

                    b.ToTable("tbl_mahalle", (string)null);
                });

            modelBuilder.Entity("Ticari.Entities.TurkiyeDb.TblPk", b =>
                {
                    b.Property<string>("Kod")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("kod")
                        .HasDefaultValueSql("((0))")
                        .IsFixedLength()
                        .UseCollation("Turkish_CI_AS");

                    b.Property<short>("PkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("pk_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("PkId"));

                    b.ToTable("tbl_pk", (string)null);
                });

            modelBuilder.Entity("Ticari.Entities.TurkiyeDb.TblSemt", b =>
                {
                    b.Property<short>("SemtId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("semt_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("SemtId"));

                    b.Property<short>("IlceId")
                        .HasColumnType("smallint")
                        .HasColumnName("ilce_id");

                    b.Property<string>("SemtAd")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("semt_ad")
                        .UseCollation("Turkish_CI_AS");

                    b.HasKey("SemtId")
                        .HasName("PK_tbl_semtler");

                    b.HasIndex(new[] { "SemtId", "IlceId" }, "IX_semt");

                    b.ToTable("tbl_semt", (string)null);
                });

            modelBuilder.Entity("Ticari.Entities.TurkiyeDb.VwTumunugoster", b =>
                {
                    b.Property<string>("IlAd")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)")
                        .HasColumnName("il_ad")
                        .UseCollation("Turkish_CI_AS");

                    b.Property<string>("IlceAd")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("ilce_ad")
                        .UseCollation("Turkish_CI_AS");

                    b.Property<string>("Kod")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("char(5)")
                        .HasColumnName("kod")
                        .IsFixedLength()
                        .UseCollation("Turkish_CI_AS");

                    b.Property<string>("MahalleAd")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("mahalle_ad")
                        .UseCollation("Turkish_CI_AS");

                    b.Property<string>("SemtAd")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("semt_ad")
                        .UseCollation("Turkish_CI_AS");

                    b.ToTable((string)null);

                    b.ToView("vw_tumunugoster", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
